 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

 jobs:
   build:
     executor: win/default     
    
     steps:
       - checkout
       - run: dotnet build
       - run: dotnet test --no-build --logger "trx"
       - run:
           name: test results
           when: always
           command: |
             dotnet tool install -g trx2junit
             echo 'export PATH="$PATH:/root/.dotnet/tools"' >> "$BASH_ENV"
             trx2junit test/CommandAPI.Tests/TestResults/*.trx
       - store_test_results:
           path: test/CommandAPI.Tests/TestResults
       - store_artifacts:
           path: test/CommandAPI.Tests/TestResults
           destination: TestResults